In [3]:

def te_none(a):
    print(a is None)

te_none(None)

True


In [136]:
# item
a = torch.tensor([3])
print(a.item())

3


In [143]:
# 正确率
y_hat = torch.tensor([[0.5, 0.2, 0.3], [0.1, 0.2, 0.7]])
y = torch.tensor([0, 2])
print('accu', (y_hat.argmax(dim=1) == y).sum().item() / y.shape[0])

1.0

In [141]:
# shape
a = torch.rand((2,3,4))
print(a)
print(a.shape)
print(a.shape[0])

b = a.view(a.shape[0], -1)
print(b)
print(b.shape)

c = torch.tensor([3,4,5,6])
d = torch.tensor([3,2,5,6])
print(c.shape)
print(c == d)

tensor([[[0.6961, 0.0919, 0.9415, 0.8009],
         [0.5881, 0.0337, 0.0220, 0.5437],
         [0.8957, 0.8959, 0.8249, 0.2478]],

        [[0.4575, 0.0767, 0.0032, 0.4745],
         [0.8499, 0.3540, 0.8056, 0.4436],
         [0.9746, 0.6835, 0.5805, 0.0035]]])
torch.Size([2, 3, 4])
2
tensor([[0.6961, 0.0919, 0.9415, 0.8009, 0.5881, 0.0337, 0.0220, 0.5437, 0.8957,
         0.8959, 0.8249, 0.2478],
        [0.4575, 0.0767, 0.0032, 0.4745, 0.8499, 0.3540, 0.8056, 0.4436, 0.9746,
         0.6835, 0.5805, 0.0035]])
torch.Size([2, 12])
torch.Size([4])
tensor([ True, False,  True,  True])


In [138]:
# argmax
a = torch.tensor([
    [9,2,1], 
    [4,5,8]])

print('a.argmax(dim=0), ', a.argmax(dim=0))

print('a.argmax(dim=1)', a.argmax(dim=1))


a.argmax(dim=0),  tensor([0, 1, 1])
a.argmax(dim=1) tensor([0, 2])


In [6]:
# net.parametes()
import torch
l1 = torch.nn.Linear(3,4, bias=True)
l2 = torch.nn.Linear(4,5, bias=True)
net = torch.nn.Sequential(l1, l2)
print(l1)
print(l2, '\n')

w = torch.empty(3, 5)
torch.nn.init.normal(w, mean=100, std=10)
print(w)

print('parameters ----')

# 因为有 weight, bias 所以有 4 个参数层
for p in net.parameters():
    print(p)


Linear(in_features=3, out_features=4, bias=True)
Linear(in_features=4, out_features=5, bias=True) 

tensor([[ 93.0093, 103.5457,  98.6235,  94.2734, 113.2469],
        [ 80.6863,  91.8545,  99.9626, 102.9370, 108.2044],
        [111.8902,  94.7749,  71.7258,  94.8969,  79.8990]])
parameters ----
Parameter containing:
tensor([[-0.3172,  0.0427,  0.3532],
        [-0.5551, -0.0534,  0.0465],
        [-0.3285,  0.4402, -0.0092],
        [-0.0052,  0.0458,  0.2975]], requires_grad=True)
Parameter containing:
tensor([ 0.1107,  0.4387,  0.2176, -0.4730], requires_grad=True)
Parameter containing:
tensor([[ 0.0706,  0.0585,  0.2501,  0.3465],
        [ 0.2940, -0.2512,  0.3615,  0.4334],
        [-0.2040,  0.0042, -0.1167,  0.1213],
        [ 0.1963, -0.3190, -0.1602,  0.3305],
        [-0.0997, -0.2576, -0.2656,  0.0197]], requires_grad=True)
Parameter containing:
tensor([-0.2416,  0.4389,  0.2887,  0.4688, -0.4241], requires_grad=True)
ipykernel_launcher:9: UserWarning: nn.init.normal is now

In [7]:
# torch.linspace
import math
x = torch.linspace(-math.pi, math.pi, 2000)
print(x)


tensor([-3.1416, -3.1384, -3.1353,  ...,  3.1353,  3.1384,  3.1416])


In [8]:
# with torch.no_grad() 子树不记录梯度
x = torch.randn(10, 5, requires_grad = True)
y = torch.randn(10, 5, requires_grad = True)
z = torch.randn(10, 5, requires_grad = True)

n = x + y + z
print(n.requires_grad, '\n -----')

with torch.no_grad():
    w = x + y + z
    print(w.requires_grad)
    print(w.grad_fn)
print(w.requires_grad)

True 
 -----
False
None
False


In [134]:
# pow
a = torch.tensor([[1,2,3], [2,3,4]])
print(a.pow(3).sum())


tensor(135)


3

In [10]:
# is vs ==
a = 1
b = 1
print(a==b)
print(a is b)
print('---')


a = 2.0
b = 2.0
print(a == b)
print(a is b)
print('---')

a = {'value': 1}
b = {'value': 1}
print(a == b)
print(a is b)
print(id(a) == id(b))

True
True
---
True
False
---
True
False
False


In [63]:
# unsequeeze 膨胀

a = torch.tensor([1,2,3,4,5])
b = torch.tensor([1,2,3])
# print(a.unsqueeze(0))
# print(a.unsqueeze(1))
# print(a.shape)


x = torch.tensor([1,2,3,4,5])
b = torch.tensor([1,2,3])

print(x.shape)


sx = x.unsqueeze(1)
print(sx.shape)

xx = sx.pow(b)
print(xx)


torch.Size([5])
torch.Size([5, 1])
tensor([[  1,   1,   1],
        [  2,   4,   8],
        [  3,   9,  27],
        [  4,  16,  64],
        [  5,  25, 125]])


In [92]:
# nn.Linear


m = torch.nn.Linear(3, 2, bias=True) # 创建 Linear 层时会随机初始化 w, b

# 5 x 3 矩阵
input = torch.tensor([
        [1,  2,  3],
        [5, 5,  1],
        [1,  3, 5],
        [ 1,  0, -1],
        [ 9, 1, -3]], dtype=torch.float32)

print(m.bias, m.weight)

print('output', m(input))

Parameter containing:
tensor([0.4926, 0.3428], requires_grad=True) Parameter containing:
tensor([[ 0.2038, -0.3172, -0.0947],
        [-0.1097, -0.0581,  0.5024]], requires_grad=True)
output tensor([[-0.2220,  1.6240],
        [-0.1690,  0.0059],
        [-0.7285,  2.5707],
        [ 0.7911, -0.2694],
        [ 2.2939, -2.2102]], grad_fn=<AddmmBackward>)


In [122]:
# nn.Flatten

m0 = torch.nn.Flatten(0)
m1 = torch.nn.Flatten(1)
m2 = torch.nn.Flatten(2)
m3 = torch.nn.Flatten(3)

t = torch.tensor([[[3,2,3], [4,5,3]]])


print(m0(t))
print(m1(t))
print(m2(t))

tensor([3, 2, 3, 4, 5, 3])
tensor([[3, 2, 3, 4, 5, 3]])
tensor([[[3, 2, 3],
         [4, 5, 3]]])
